# Configuração básica do Netlify
[build]
  # Diretório onde o build final será gerado (normalmente "build" para Create React App)
  publish = "build"
  
  # Comando de build que será executado pelo Netlify
  command = "npm run build"

# Configurações específicas para redirecionamentos e rotas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
