[build]
  publish = "dist"  # Se estiver usando Vite, a pasta correta é "dist", não "build"
  command = "npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
